### ISSUE TITLE
Project review by Nicholai Mauritzson

### ISSUE THREAD

**Issue by nicholaimauritzson** [teokem/project-work-2018-ndsim#1]
_I have read through you Jupyter project and have some feedback. I have based my review on the project requirements as given in the course description: https://github.com/mlund/jupyter-course_

I really liked the fact that you allows the reader to input his/her own parameters to the the changes. This was generally an interesting read but I had hoped to have more of an basic introduction before going into the details. I know, this was not really part of the project but as it stands I believe only people with prior knowledge or even in your same field would be able to follow it thoroughly.

Based on the criteria given in the course description I did find some things missing from the report:
- You have not included the use of the pandas package and methods for this project. 
- You did not read in "large data sets" or load data from a text file. _(I would think generated data would also work fine, but this was written in the requirements. Alternatively you could use pandas to import a pre-generated data set.)_
- You did not save data to disk "processed or generated data" _(Something which I forgot to do as well. I think the purpose is to show that we are able to implement the code)_
- Your figures does not seem to conform to the standard widths given in the requirements. _(Single column text should have a 183mm wide images/figures)_
- You have not included any composite plots ("insets or multiple panels"). _(Maybe you could simple summarize a few of the plots in a sub plot configuration to show the progress for "ease-of-read")_
- There is no digital object identifier (DOI) attached with the project. _(I made my DOI through http://zenodo.org/ linking it with GitHub)_

I am not sure if all the things written in the project requirements are needed to complete the project but I thought I would note what I found.

Lastly, I thought to note that the binder link does not work due to failure to use the "nestle" package.

Overall your text and content was clear and well laid out with a natural flow.
Thank you for a nice report.

Regards,
Nicholai

**Comment by ndsim** [comment]
Thanks for your review!

So I did read through the requirements before submitting -- I tried for a while to get zenodo to work but could make my repository visible to it. The first three points I don't consider relevant to the point of the notebook, but I suppose I could have adapted it to use pandas. Yes, I did forget to do an inset plot (though I don't like forcing projects in this way to have certain requirements...), your idea is good for this.

I knew something would go wrong... thanks for the binder heads up!

I do agree that a more basic introduction is necessary. Thanks for that.

Best wishes,
Nathan
