### ISSUE TITLE
Review by Camille Garcia

### ISSUE THREAD

**Issue by CamilleAny** [teokem/project-work-2018-ndsim#2]
# Review of “A guide to nested sampling, featuring your particle!” by Nathan Simpson

_Date: 10/01/19_

## Documentation :

- **Includes rich documentation using Markdown**
Yes, this notebook is rich in documentation using figures, links and equations. Furthermore, an effort in scientific popularisation was provided to make this notebook accessible.

- **Includes instruction on how to run the notebook**
Partially,  you give the instruction but in your README file you imply that your environment name is “ns”, instead of “stats”. 

- **Includes the required packages in en environment file**
No, to make your notebook run I had to add modification to your environment file (remove nestle and add Matplotlib). 

- **Is reproducible**
Yes and thanks to your clear writing and comments your code is easy to follow

## Input/Output :

- **Uses pandas to read large data sets or numpy to load data from text files**
Yes, numpy was used to load data

- **Uses pandas to save to disk the processed or generated data** 
No

## Scientific computing/data processing :

- **Perform data operations using numpy, scipy, pandas or equivalent**
Yes

## Data visualisation : 

- **Includes a least one composite plot**
No

- **Create plots of publication ready quality**
    - The figures width is 89nm or 183nm
Yes
    - The axes are labelled
Yes
    - The front size are sufficiently large
Yes
    - The figure are saved as rasterised images (300 dpi) or vector art
No 

## Version control, sharing and archiving : 

- **Is archived in a repository with a digital object identifier (DOI)**
No

## Conclusion :

Apart from the tiny issue with the environment, I think that your notebook is nicely written and your code is easy to follow and it uses a lot of comments. And even if I am not in the target audience of this notebook, I still succeed to have a general overview of your guide.

Best,
Camille

**Comment by ndsim** [comment]
Thank you for your comments Camille. Sorry for the problems with the environment, I think I must have got some commits mixed up, as I had a working version without the errors you mention.

I should definitely consider my target audience more, but felt I was under too much time pressure to take this fully into consideration.

Nathan
